site_name: "ModelManagementFramework"
theme:
  name: material
  palette:
    primary: black
#  logo: assets/logo.svg
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
nav:
  - Home:
    - Главное: index.md
    - Коммуникация: rpc.md
    - Логирование: log.md
    - Масштабирование: scale.md
    - Балансировка: balance.md

  - Для ML-разработчика:
      - Быстрый старт: quick.md
      - Дескрипторы: descriptors.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search:
      lang:
        - en
        - ru
  - autorefs
  - mkdocstrings
  - mermaid2
repo_url: https://github.com/mm-framework
